In [1]:
import  numpy as np
import pandas as pd

In [2]:
df = pd.read_excel(r"C:\Users\ASUS  VIVOBOOK\Downloads\PROJECTS\CHURN_DA\Churn_Unclean_Project.xlsx")

In [3]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            542 non-null    str
 1   Customer_Name          533 non-null    str
 2   Gender                 536 non-null    str
 3   Age                    536 non-null    float64
 4   State                  531 non-null    str
 5   City                   539 non-null    str
 6   Tenure_Months          534 non-null    float64
 7   Subscription_Type      530 non-null    str
 8   Monthly_Charges        529 non-null    float64
 9   Total_Charges          533 non-null    float64
 10  Contract_Type          538 non-null    str
 11  Payment_Method         526 non-null    str
 12  Internet_Service       535 non-null    str
 13  Tech_Support           530 non-null    str
 14  Senior_Citizen         534 non-null    str
 15  Dependents             539 non-null    str
 16  Churn                  538 non-null    str
 17  Last_Interaction_Date  539 non-null    str
dtypes: float64(4), str(14)
memory usage: 76.3 KB

In [5]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  536.000000     534.000000       529.000000     533.000000
mean    44.399254      36.406367      1335.269206   49745.287336
std     18.556837      20.669599       715.972838   41644.111657
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       756.570000   18770.290000
50%     44.000000      38.000000      1306.800000   40649.600000
75%     57.000000      54.000000      1900.650000   75647.400000
max    165.000000      72.000000      2492.510000  171429.830000

In [6]:
df.shape

(542, 18)

In [7]:
# Check Missing Values

df.isnull().sum()

#df.isnull().sum().sum()  # counts NaN in whole table

Customer_ID               0
Customer_Name             9
Gender                    6
Age                       6
State                    11
City                      3
Tenure_Months             8
Subscription_Type        12
Monthly_Charges          13
Total_Charges             9
Contract_Type             4
Payment_Method           16
Internet_Service          7
Tech_Support             12
Senior_Citizen            8
Dependents                3
Churn                     4
Last_Interaction_Date     3
dtype: int64

In [8]:
# Check Duplicate Values

df.duplicated().sum()

np.int64(7)

In [9]:
# Remove duplicates

df.drop_duplicates(inplace=True)   # used inplace so it will change in original dataframe

In [10]:
df.shape  # after removing duplicate

(535, 18)

In [11]:
df.replace(['NULL', 'N/A', '', ' '], np.nan, inplace = True)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,C5005,Sneha Jain,Female,115.0,Gujarat,Surat,1.0,NaN,1633.64,1707.64,Two Year,Debit Card,Cable,No,No,Yes,No,13-03-2026
538,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-to-Month,UPI,DSL,Yes,No,No,No,26-12-2025
539,C5007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,14-01-2025
540,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,BASIC,1200.00,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,28-02-2025
541,C5009,Rahul Singh,Male,25.0,UP,Kanpur,30.0,Basic,1341.52,NaN,Month-to-Month,Credit Card,Cable,No,No,Yes,No,29-11-2025

In [12]:
df.isnull().sum()

Customer_ID               0
Customer_Name             8
Gender                    5
Age                       6
State                    10
City                      5
Tenure_Months             7
Subscription_Type        11
Monthly_Charges          12
Total_Charges             8
Contract_Type             3
Payment_Method           15
Internet_Service          6
Tech_Support             11
Senior_Citizen            7
Dependents                2
Churn                     3
Last_Interaction_Date     2
dtype: int64

In [13]:
# remove extra spaces

df = df.apply(lambda x:x.str.strip() if x.dtype == "str" else x)

In [14]:
# Value Counts

df["Subscription_Type"].value_counts()

Subscription_Type
Premium     184
Standard    169
Basic       167
basic         2
BASIC         2
Name: count, dtype: int64

In [15]:
# Proper Case 

df["Customer_Name"] = df["Customer_Name"].str.title()
df["State"] = df["State"].str.title()
df["City"] = df["City"].str.title()
df["Subscription_Type"] = df["Subscription_Type"].str.title()
df["Contract_Type"] = df["Contract_Type"].str.title()
df["Churn"] = df["Churn"].str.title()
df["Gender"] = df["Gender"].str.title()

# df = df.apply(lambda x: x.str.title() if x.dtype == "str" else x)

In [16]:
df["Subscription_Type"].value_counts()

Subscription_Type
Premium     184
Basic       171
Standard    169
Name: count, dtype: int64

In [17]:
df['Churn'].value_counts()

Churn
No     405
Yes    127
Name: count, dtype: int64

In [18]:
# Remove Invalid Age

df = df[(df['Age'] >= 18 ) & (df['Age'] <= 100)]

In [19]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  519.000000     512.000000       508.000000     511.000000
mean    43.400771      36.412109      1331.267028   50192.694599
std     15.480629      20.539878       717.680999   41263.136797
min     18.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       757.845000   18954.440000
50%     43.000000      38.000000      1300.700000   40787.720000
75%     56.500000      54.000000      1881.492500   75126.770000
max     70.000000      72.000000      2492.510000  171429.830000

In [20]:
# Remove Negative Charges

df = df[df['Monthly_Charges'] >= 0]

df = df[df['Total_Charges'] >= 0]

In [21]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  492.000000     487.000000       492.000000     492.000000
mean    43.191057      36.059548      1359.222033   50363.987561
std     15.401619      20.465130       653.133221   39760.135287
min     18.000000       1.000000       302.540000     354.120000
25%     30.000000      19.000000       762.940000   19129.100000
50%     43.000000      38.000000      1308.510000   40668.695000
75%     56.000000      53.000000      1889.437500   74393.410000
max     70.000000      72.000000      2492.510000  171429.830000

In [22]:
df.shape

(492, 18)

In [23]:
# Convert Date

df['Last_Interaction_Date'] = pd.to_datetime(df['Last_Interaction_Date'], errors = 'coerce')

In [24]:
# Fill Missing Values

df['Tech_Support'] = df['Tech_Support'].fillna("No")

df['Payment_Method'] = df['Payment_Method'].fillna("Unknown")

df['Monthly_Charges'] = df['Monthly_Charges'].fillna(df['Monthly_Charges'].mean())

df['Tenure_Months'] = df['Tenure_Months'].fillna(df['Tenure_Months'].mean())

df['Age'] = df['Age'].fillna(df['Age'].mean())

df['Last_Interaction_Date'] = df['Last_Interaction_Date'].fillna(df['Last_Interaction_Date'].median())

In [25]:
# Feature Engineering

# Customer lifetime value

df['Customer_Value'] = df['Monthly_Charges'] * df['Tenure_Months']

In [26]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,2025-12-10,93627.08
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,2025-08-24,7215.39
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,2026-02-04,1884.12
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-To-Month,UPI,DSL,Yes,No,No,No,2025-08-24,140618.10
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,2025-08-24,125182.26

In [27]:
# Monthly Revenue

df['Monthly_Revenue'] = df['Monthly_Charges']

In [28]:
# Tenure Group "0-12" , "13-24", "25-48", "49-72"

bins = 0,12,24,48,72
label = ["0-12 month" , "13-24 month", "25-48 month", "49-72 month"]

df['Tenure_Group'] = pd.cut(df['Tenure_Months'], bins = bins, labels = label)

In [29]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Tenure_Group
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,...,UPI,Fiber,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,49-72 month
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,Debit Card,5G,No,No,No,Yes,2025-08-24,7215.39,555.03,13-24 month
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,...,Debit Card,Cable,Yes,No,No,No,2026-02-04,1884.12,314.02,0-12 month
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,...,UPI,DSL,Yes,No,No,No,2025-08-24,140618.10,2008.83,49-72 month
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,...,Cash,Cable,Yes,Yes,Yes,No,2025-08-24,125182.26,2196.18,49-72 month

In [30]:
# Senior Citizen Flag

df['Senior_Flag'] = np.where(df['Age'] >= 60, "Senior", "Adult")

In [31]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Tenure_Group,Senior_Flag
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,...,Fiber,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,49-72 month,Adult
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,5G,No,No,No,Yes,2025-08-24,7215.39,555.03,13-24 month,Adult
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,...,Cable,Yes,No,No,No,2026-02-04,1884.12,314.02,0-12 month,Adult
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,...,DSL,Yes,No,No,No,2025-08-24,140618.10,2008.83,49-72 month,Adult
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,...,Cable,Yes,Yes,Yes,No,2025-08-24,125182.26,2196.18,49-72 month,Senior

In [32]:
# Churn Flag

df['Churn_Flag'] = df['Churn'].map({"Yes":1, "No":0})

In [33]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Tenure_Group,Senior_Flag,Churn_Flag
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,...,Yes,No,Yes,No,2025-12-10,93627.08,1614.26,49-72 month,Adult,0.0
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,No,No,No,Yes,2025-08-24,7215.39,555.03,13-24 month,Adult,1.0
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,...,Yes,No,No,No,2026-02-04,1884.12,314.02,0-12 month,Adult,0.0
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,...,Yes,No,No,No,2025-08-24,140618.10,2008.83,49-72 month,Adult,0.0
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,...,Yes,Yes,Yes,No,2025-08-24,125182.26,2196.18,49-72 month,Senior,0.0

In [34]:
#Final Check

df.info()

<class 'pandas.DataFrame'>
Index: 492 entries, 0 to 540
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            492 non-null    str
 1   Customer_Name          487 non-null    str
 2   Gender                 488 non-null    str
 3   Age                    492 non-null    float64
 4   State                  485 non-null    str
 5   City                   487 non-null    str
 6   Tenure_Months          492 non-null    float64
 7   Subscription_Type      486 non-null    str
 8   Monthly_Charges        492 non-null    float64
 9   Total_Charges          492 non-null    float64
 10  Contract_Type          490 non-null    str
 11  Payment_Method         492 non-null    str
 12  Internet_Service       486 non-null    str
 13  Tech_Support           492 non-null    str
 14  Senior_Citizen         486 non-null    str
 15  Dependents             491 non-null    str
 16  Churn                  490 non-null    str
 17  Last_Interaction_Date  492 non-null    datetime64[us]
 18  Customer_Value         492 non-null    float64
 19  Monthly_Revenue        492 non-null    float64
 20  Tenure_Group           492 non-null    category
 21  Senior_Flag            492 non-null    str
 22  Churn_Flag             490 non-null    float64
dtypes: category(1), datetime64[us](1), float64(7), str(14)
memory usage: 88.9 KB

In [35]:
df.describe()

,Age,Tenure_Months,Monthly_Charges,Total_Charges,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Churn_Flag
count,492.000000,492.000000,492.000000,492.000000,492,492.000000,492.000000,490.000000
mean,43.191057,36.059548,1359.222033,50363.987561,2025-09-05 13:10:14.634146,50231.467233,1359.222033,0.236735
min,18.000000,1.000000,302.540000,354.120000,2025-01-01 00:00:00,379.700000,302.540000,0.000000
25%,30.000000,19.000000,762.940000,19129.100000,2025-08-24 00:00:00,19125.137500,762.940000,0.000000
50%,43.000000,37.000000,1308.510000,40668.695000,2025-08-24 00:00:00,40701.195000,1308.510000,0.000000
75%,56.000000,53.000000,1889.437500,74393.410000,2025-08-24 00:00:00,74097.160000,1889.437500,0.000000
max,70.000000,72.000000,2492.510000,171429.830000,2026-12-06 00:00:00,171658.830000,2492.510000,1.000000
std,15.401619,20.360662,653.133221,39760.135287,NaN,39647.442978,653.133221,0.425513

In [36]:
df.isnull().sum()

Customer_ID              0
Customer_Name            5
Gender                   4
Age                      0
State                    7
City                     5
Tenure_Months            0
Subscription_Type        6
Monthly_Charges          0
Total_Charges            0
Contract_Type            2
Payment_Method           0
Internet_Service         6
Tech_Support             0
Senior_Citizen           6
Dependents               1
Churn                    2
Last_Interaction_Date    0
Customer_Value           0
Monthly_Revenue          0
Tenure_Group             0
Senior_Flag              0
Churn_Flag               2
dtype: int64

In [37]:
pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in C:\Users\ASUS  VIVOBOOK\AppData\Local\Programs\Python\Python311\Lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in C:\Users\ASUS  VIVOBOOK\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in C:\Users\ASUS  VIVOBOOK\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\ASUS  VIVOBOOK\AppData\Roaming\Python\Python311\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [38]:
# Import Clean dataset in CSV

df.to_csv("Clean_Churn_Data.csv", index = False)

In [39]:
# Export into SQL Server

from sqlalchemy import create_engine
from urllib.parse import quote_plus

# Set your exact server name from SSMS
host = r"PRINCE\SQLEXPRESS"
database = "churndb"

# Encode the driver name safely
driver = quote_plus("ODBC Driver 17 for SQL Server")

# Connection string using trusted_connection=yes (No username/password needed)
engine = create_engine(f"mssql+pyodbc://@{host}/{database}?driver={driver}&trusted_connection=yes")

In [40]:
# Write DataFrame to SQL Server

df.to_sql("customer_churn", con = engine, if_exists="replace", index=False)

37